### ISSUE TITLE
Wrong query strings for variables when requesting data via the UI 

### ISSUE THREAD

**Issue by MartinPontius** [52North/MariDataHarvest#16]
When downloading data via the UI, a GET request is made, e.g., against the following url:

`https://harvester.maridata.dev.52north.org/EnvDataAPI/request_env_data?date_lo=2021-04-02T00%3A00&date_hi=2021-04-03T21%3A00&lat_lo=45.8&lat_hi=51.3&lon_lo=-5.7&lon_hi=2.1&csvUpload=&var-%24%24-Wave-%24%24-VTPK=VTPK&var-%24%24-Wave-%24%24-VPED=VPED&var-%24%24-Wave-%24%24-VHM0=VHM0&var-%24%24-Physical-%24%24-vo=vo&var-%24%24-Physical-%24%24-uo=uo&var-%24%24-Physical-%24%24-so=so&var-%24%24-GFS-%24%24-Temperature_surface=Temperature_surface&var-%24%24-GFS-%24%24-u-component_of_wind_maximum_wind=u-component_of_wind_maximum_wind&var-%24%24-GFS-%24%24-v-component_of_wind_maximum_wind=v-component_of_wind_maximum_wind&format=netcdf`

This produces a 400 Error 

> No variables are selected

The correct url should be:

`https://harvester.maridata.dev.52north.org/EnvDataAPI/request_env_data?date_lo=2021-04-02T00%3A00&date_hi=2021-04-03T21%3A00&lat_lo=45.8&lat_hi=51.3&lon_lo=-5.7&lon_hi=2.1&Wave=VHM0&Wave=VPED&Wave=VTPK&Physical=so&Physical=vo&Physical=uo&GFS=u-component_of_wind_maximum_wind&GFS=v-component_of_wind_maximum_wind&GFS=Temperature_surface&format=netcdf`

**Comment by EHJ-52n** [comment]
Fixed by updating the complete deployment. The static files for the WebUI are served by the "web" service, hence rebuilding of its image is required when any static file is changed.
