### ISSUE TITLE
Update old time ranges for CMEMS products

### ISSUE THREAD

**Issue by MartinPontius** [52North/MariDataHarvest#19]
Update old time ranges for CMEMS products, see for example https://github.com/52North/MariDataHarvest/blob/main/EnvironmentalData/weather.py#L55

If possible, do not hard-code the time range, but take it e.g. from CMEMS website or regularly updated metadata docs.

Example requests that throws an error because of this:

https://harvester.maridata.dev.52north.org/EnvDataAPI/request_env_data?date_lo=2019-06-02T00%3A00&date_hi=2019-06-03T15%3A00&lat_lo=52.897&lat_hi=54.263&lon_lo=1.507&lon_hi=3.283&Wave=VHM0_WW&Wave=VMDR_SW2&Wave=VMDR_SW1&Wave=VMDR&Wave=VTM10&Wave=VTPK&Wave=VPED&Wave=VTM02&Wave=VMDR_WW&Wave=VTM01_SW2&Wave=VHM0_SW1&Wave=VTM01_SW1&Wave=VSDX&Wave=VSDY&Wave=VHM0&Wave=VTM01_WW&Wind=surface_downward_eastward_stress&Wind=wind_stress_divergence&Wind=northward_wind&Wind=sampling_length&Wind=wind_speed_rms&Wind=wind_vector_curl&Wind=northward_wind_rms&Wind=eastward_wind&Wind=wind_speed&Wind=wind_vector_divergence&Wind=wind_stress&Wind=wind_stress_curl&Wind=eastward_wind_rms&Wind=surface_type&Wind=surface_downward_northward_stress&Physical=mlotst&Physical=siconc&Physical=usi&Physical=thetao&Physical=sithick&Physical=bottomT&Physical=vsi&Physical=vo&Physical=uo&Physical=so&Physical=zos&GFS=Temperature_surface&GFS=Wind_speed_gust_surface&GFS=u-component_of_wind_maximum_wind&GFS=v-component_of_wind_maximum_wind&GFS=Dewpoint_temperature_height_above_ground&GFS=Relative_humidity_height_above_ground&GFS=U-Component_Storm_Motion_height_above_ground_layer&GFS=V-Component_Storm_Motion_height_above_ground_layer&format=netcdf

`Error occurred while retrieving Wave data: ('Error:', ValueError("cannot guess the engine, b'\\n\\n\\n\\n\\n\\n\\n\\n' is not the signature of any supported file format did you mean to pass a string for a path instead?"), 'Request: ', 'https://nrt.cmems-du.eu/motu-web/Motu?action=productdownload&service=GLOBAL_ANALYSIS_FORECAST_WAV_001_027-TDS&product=global-analysis-forecast-wav-001-027&x_lo=1.3239999999999998&x_hi=3.466&y_lo=52.714&y_hi=54.446&t_lo=2019-06-01T21:00:00Z&t_hi=2019-06-03T21:00:00Z&mode=console') Error occurred while retrieving Wind data: ('Error:', ValueError("cannot guess the engine, b'<?xml ve' is not the signature of any supported file format did you mean to pass a string for a path instead?"), 'Request: ', 'https://nrt.cmems-du.eu/motu-web/Motu?action=productdownload&service=WIND_GLO_WIND_L4_NRT_OBSERVATIONS_012_004-TDS&product=CERSAT-GLO-BLENDED_WIND_L4-V6-OBS_FULL_TIME_SERIE&x_lo=1.174&x_hi=3.616&y_lo=52.564&y_hi=54.596&t_lo=2019-06-01T18:00:00Z&t_hi=2019-06-04T00:00:00Z&mode=console') Error occurred while retrieving Physical data: ('Error:', ValueError("cannot guess the engine, b'\\n\\n\\n\\n\\n\\n\\n\\n' is not the signature of any supported file format did you mean to pass a string for a path instead?"), 'Request: ', 'https://nrt.cmems-du.eu/motu-web/Motu?action=productdownload&service=GLOBAL_ANALYSIS_FORECAST_PHY_001_024-TDS&product=global-analysis-forecast-phy-001-024&x_lo=1.3239999999999998&x_hi=3.466&y_lo=52.714&y_hi=54.446&t_lo=2019-05-31T12:00:00Z&t_hi=2019-06-04T12:00:00Z&z_lo=0.49&z_hi=0.5&mode=console') `

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue, can you guide me a bit more on steps @MartinPontius

**Comment by MartinPontius** [comment]
Fixed in [04727a8f7dee019c7fa1dfa7b7052a0f5b1ac40f](https://github.com/52North/MariDataHarvest/commit/04727a8f7dee019c7fa1dfa7b7052a0f5b1ac40f).
