### ISSUE TITLE
Fix wind parameter retrieval from CMEMS

### ISSUE THREAD

**Issue by EHJ-52n** [52North/MariDataHarvest#67]

**Comment by PasunuriSrinidhi** [comment]
I would like to work on this issue, can you please assign this to me

**Comment by MartinPontius** [comment]
Fixed in [04727a8f7dee019c7fa1dfa7b7052a0f5b1ac40f](https://github.com/52North/MariDataHarvest/commit/04727a8f7dee019c7fa1dfa7b7052a0f5b1ac40f).
